#Configuration.
[mqtt]
server="tcp://localhost:1883"
user="mqtt-user"
password="mqtt-password"

[gateway]
mac="gw-mac"

[device]
eui="0000000000000000"
address="07262b83"
network_session_key="3bc0ddd455d320a6f36ff6f2a25057d0"
application_session_key="00de01b45b59a4df9cc2b3fa5eb0fe7c"

[data_rate]
bandwith=500
spread_factor=8
bit_rate=0

[rx_info]
channel=0
code_rate="4/5"
crc_status=1
frequency=902300000
lora_snr=7.0
rf_chain=1
rssi=-57

